apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    uid: prometheus-uid
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    readOnly: false
    jsonData:
      httpMethod: GET
