{
 "title": "MetricsGenerator",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "/metrics-generator/counter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "test_generator_counter_un_total{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics-generator/counter",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "test_generator_counter_un_total{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics-generator/up-down-counter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "test_generator_up_down_counter_un{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics-generator/up-down-counter",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "test_generator_up_down_counter_un{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics-generator/gauge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "test_generator_gauge_un{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics-generator/gauge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "test_generator_gauge_un{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics-generator/counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "test_generator_counter_un_total{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics-generator/up-down-counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "test_generator_up_down_counter_un{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics-generator/gauge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "test_generator_gauge_un{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics-generator/histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "test_generator_histogram_un_bucket{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics-generator/histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "test_generator_histogram_un_bucket{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}