{
 "title": "Producs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Requests by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, path) (http_requests_total{job=\"Demo.Api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Time Buckets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, path) (request_duration_milliseconds_bucket{job=\"Demo.Api\", le!=\"+Inf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pending Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "queue_pending_items{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Messages Processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "messages_processed_items_total{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Products",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_products{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_used_bytes{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Reponses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(status) (http_requests_total{job=\"Demo.Api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precessing Message Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "queue_processing_time_milliseconds{job=\"Demo.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}